sepolia:
    # dev
    market:
        proxy: ''
        impl: ''
        admin: ''

    # local
    # market:
    #     proxy: ''
    #     impl: ''
    #     admin: ''

ethereum:
    market:
        proxy: ''
        impl: ''
        admin: ''
