sepolia:
    chainId: 11155111
    url: ''
    deployerPrivateKey: ''
    main: ''
    wrappedEther: ''

ethereum:
    chainId: 1
    url: ''
    deployerPrivateKey: ''
    main: ''
    wrappedEther: ''
