name: 'DigitalOriginal'
symbol: 'DO'

sepolia:
    minAuctionDurationHours: 0.25

    # dev
    artToken:
        proxy: '0xaf99c146DC881A37a8e960d9EdC1818eEF6CaE7A'
        impl: '0xC223b0B26bD1669dfcb1773A01bb4860E8064701'
        admin: '0x6c6e09B662Ff1611826fb304A095fE34daCD1c8d'
    auctionHouse:
        proxy: '0x68748499241200b3173082567d5F38B00B8CEe06'
        impl: '0x9C8eAE30b12E6A12EFf556ea8350F45FCFCaEADc'
        admin: '0xE2B7755956382bE4a2fCE7a0e67d4BDd74770a48'

    # local
    # artToken:
    #     proxy: '0xe74D07495C9CD456574Dccb5b48cD80B59412136'
    #     impl: '0xAa0a787042094E19eEb96f3f1B608Daf76118Da3'
    #     admin: '0x23e435Dd7fd98313Da588bFb5df74A067ac9Cb98'
    # auctionHouse:
    #     proxy: '0xFaF5E7bb2EF569d89eF0Af819e54eEf780cCBc25'
    #     impl: '0xACeb70317C606B62697978FB14E3B9c42f80cAe2'
    #     admin: '0xfaa84c3EE49FBF050B850A073186A83780b01964'

ethereum:
    minAuctionDurationHours: 24
    artToken:
        proxy: '0x653cdB21a83b59374C194002Da332D683F5678aA'
        impl: '0xaeA2EBA1964E61306b2aB1A9B368a9A0c99082a1'
        admin: '0x6c54061AC5c758B12453558c846c570842B82A13'
    auctionHouse:
        proxy: '0x7bb8807250928FC57c1eb01A4B65860439F94e36'
        impl: '0x102AfdcDd59Ab6bb4dfA618243b78124BFa29670'
        admin: '0xA6D10309e4dbC8259a80e37eeF09eAd6D08f92c9'
