sepolia:
    chainId: 11155111
    url: ''
    deployerPrivateKey: ''

    main: '0x27fc066baF73Ee97Ce5b95172d82F407490D49b1'

ethereum:
    chainId: 1
    url: ''
    deployerPrivateKey: ''

    main: '0x445458607007b26dB4f80DcF0f26bd6e1A4af8A5'
