name: 'DigitalOriginal'
symbol: 'DO'

sepolia:
    minPriceUsd: 100
    minFeeUsd: 100
    regulated: true
    minAuctionDurationHours: 0.25
    artToken:
        proxy: '0xaf99c146DC881A37a8e960d9EdC1818eEF6CaE7A'
        impl: '0xC223b0B26bD1669dfcb1773A01bb4860E8064701'
        admin: '0x6c6e09B662Ff1611826fb304A095fE34daCD1c8d'
    auctionHouse:
        proxy: '0x68748499241200b3173082567d5F38B00B8CEe06'
        impl: '0x9C8eAE30b12E6A12EFf556ea8350F45FCFCaEADc'
        admin: '0xE2B7755956382bE4a2fCE7a0e67d4BDd74770a48'

ethereum:
    minPriceUsd: 100
    minFeeUsd: 100
    regulated: true
    minAuctionDurationHours: 24
    artToken:
        proxy: '0x653cdB21a83b59374C194002Da332D683F5678aA'
        impl: '0x2A87F19DC4Ff1633691813CcA5b04690c3c22862'
        admin: '0x6c54061AC5c758B12453558c846c570842B82A13'
    auctionHouse:
        proxy: '0x7bb8807250928FC57c1eb01A4B65860439F94e36'
        impl: '0xBed85fc1F272aea5aE0b0100C67ae1c691FAF500'
        admin: '0xA6D10309e4dbC8259a80e37eeF09eAd6D08f92c9'
