sepolia:
    chainId: 11155111
    url: ''
    deployerPrivateKey: ''

    usdc: '0x622333D6627BaE0a7e76F507f8E21aAed577Dd57'
    main: '0x27fc066baF73Ee97Ce5b95172d82F407490D49b1'

ethereum:
    chainId: 1
    url: ''
    deployerPrivateKey: ''

    usdc: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48'
    main: '0x445458607007b26dB4f80DcF0f26bd6e1A4af8A5'
