sepolia:
    name: 'DigitalOriginal'
    symbol: 'DO'
    minAuctionDurationHours: 0.25
    artToken:
        proxy: ''
        impl: ''
        admin: ''
    auctionHouse:
        proxy: ''
        impl: ''
        admin: ''

ethereum:
    name: 'DigitalOriginal'
    symbol: 'DO'
    minAuctionDurationHours: 24
    artToken:
        proxy: ''
        impl: ''
        admin: ''
    auctionHouse:
        proxy: ''
        impl: ''
        admin: ''
